name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Create and populate secrets file
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        mkdir app/app/env
        touch app/app/env/secrets.py
        echo SECRET_KEY="$SECRET_KEY" >> ./app/app/env/secrets.py
      shell: bash
    - name: Run Tests
      run: |
        python ./app/manage.py test
